version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://joyce:password@db:5432/joyce?sslmode=disable
      - UPLOAD_DIR=/app/uploads
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_PASS=${ADMIN_PASS:-admin}
      - GIN_MODE=${GIN_MODE:-debug}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=joyce
      - POSTGRES_USER=joyce
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joyce -d joyce"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: